/*
Mender API

Combined API specification for the features of the different Mender backend services, suitable for code generation applications 

API version: 1
Contact: support@mender.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the DeviceInventoryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceInventoryResponse{}

// DeviceInventoryResponse struct for DeviceInventoryResponse
type DeviceInventoryResponse struct {
	// Mender-assigned unique ID.
	Id *string `json:"id,omitempty"`
	// Timestamp of the most recent attribute update.
	UpdatedTs *string `json:"updated_ts,omitempty"`
	// A list of attribute descriptors.
	Attributes []AttributeResponse `json:"attributes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DeviceInventoryResponse DeviceInventoryResponse

// NewDeviceInventoryResponse instantiates a new DeviceInventoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceInventoryResponse() *DeviceInventoryResponse {
	this := DeviceInventoryResponse{}
	return &this
}

// NewDeviceInventoryResponseWithDefaults instantiates a new DeviceInventoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceInventoryResponseWithDefaults() *DeviceInventoryResponse {
	this := DeviceInventoryResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeviceInventoryResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceInventoryResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeviceInventoryResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DeviceInventoryResponse) SetId(v string) {
	o.Id = &v
}

// GetUpdatedTs returns the UpdatedTs field value if set, zero value otherwise.
func (o *DeviceInventoryResponse) GetUpdatedTs() string {
	if o == nil || IsNil(o.UpdatedTs) {
		var ret string
		return ret
	}
	return *o.UpdatedTs
}

// GetUpdatedTsOk returns a tuple with the UpdatedTs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceInventoryResponse) GetUpdatedTsOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedTs) {
		return nil, false
	}
	return o.UpdatedTs, true
}

// HasUpdatedTs returns a boolean if a field has been set.
func (o *DeviceInventoryResponse) HasUpdatedTs() bool {
	if o != nil && !IsNil(o.UpdatedTs) {
		return true
	}

	return false
}

// SetUpdatedTs gets a reference to the given string and assigns it to the UpdatedTs field.
func (o *DeviceInventoryResponse) SetUpdatedTs(v string) {
	o.UpdatedTs = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *DeviceInventoryResponse) GetAttributes() []AttributeResponse {
	if o == nil || IsNil(o.Attributes) {
		var ret []AttributeResponse
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceInventoryResponse) GetAttributesOk() ([]AttributeResponse, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *DeviceInventoryResponse) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given []AttributeResponse and assigns it to the Attributes field.
func (o *DeviceInventoryResponse) SetAttributes(v []AttributeResponse) {
	o.Attributes = v
}

func (o DeviceInventoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceInventoryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.UpdatedTs) {
		toSerialize["updated_ts"] = o.UpdatedTs
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeviceInventoryResponse) UnmarshalJSON(data []byte) (err error) {
	varDeviceInventoryResponse := _DeviceInventoryResponse{}

	err = json.Unmarshal(data, &varDeviceInventoryResponse)

	if err != nil {
		return err
	}

	*o = DeviceInventoryResponse(varDeviceInventoryResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "updated_ts")
		delete(additionalProperties, "attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeviceInventoryResponse struct {
	value *DeviceInventoryResponse
	isSet bool
}

func (v NullableDeviceInventoryResponse) Get() *DeviceInventoryResponse {
	return v.value
}

func (v *NullableDeviceInventoryResponse) Set(val *DeviceInventoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceInventoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceInventoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceInventoryResponse(val *DeviceInventoryResponse) *NullableDeviceInventoryResponse {
	return &NullableDeviceInventoryResponse{value: val, isSet: true}
}

func (v NullableDeviceInventoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceInventoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


