/*
Mender API

Combined API specification for the features of the different Mender backend services, suitable for code generation applications

API version: 1
Contact: support@mender.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AbortDeploymentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AbortDeploymentRequest{}

// AbortDeploymentRequest struct for AbortDeploymentRequest
type AbortDeploymentRequest struct {
	Status string `json:"status"`
}

type _AbortDeploymentRequest AbortDeploymentRequest

// NewAbortDeploymentRequest instantiates a new AbortDeploymentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAbortDeploymentRequest(status string) *AbortDeploymentRequest {
	this := AbortDeploymentRequest{}
	this.Status = status
	return &this
}

// NewAbortDeploymentRequestWithDefaults instantiates a new AbortDeploymentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAbortDeploymentRequestWithDefaults() *AbortDeploymentRequest {
	this := AbortDeploymentRequest{}
	return &this
}

// GetStatus returns the Status field value
func (o *AbortDeploymentRequest) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AbortDeploymentRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AbortDeploymentRequest) SetStatus(v string) {
	o.Status = v
}

func (o AbortDeploymentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AbortDeploymentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *AbortDeploymentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAbortDeploymentRequest := _AbortDeploymentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAbortDeploymentRequest)

	if err != nil {
		return err
	}

	*o = AbortDeploymentRequest(varAbortDeploymentRequest)

	return err
}

type NullableAbortDeploymentRequest struct {
	value *AbortDeploymentRequest
	isSet bool
}

func (v NullableAbortDeploymentRequest) Get() *AbortDeploymentRequest {
	return v.value
}

func (v *NullableAbortDeploymentRequest) Set(val *AbortDeploymentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAbortDeploymentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAbortDeploymentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAbortDeploymentRequest(val *AbortDeploymentRequest) *NullableAbortDeploymentRequest {
	return &NullableAbortDeploymentRequest{value: val, isSet: true}
}

func (v NullableAbortDeploymentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAbortDeploymentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
