/*
Mender API

Combined API specification for the features of the different Mender backend services, suitable for code generation applications 

API version: 1
Contact: support@mender.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ErrorExt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorExt{}

// ErrorExt Error descriptor with additional metadata.
type ErrorExt struct {
	// Description of the error.
	Error string `json:"error"`
	// Request ID (same as in X-MEN-RequestID header).
	RequestId *string `json:"request_id,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _ErrorExt ErrorExt

// NewErrorExt instantiates a new ErrorExt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorExt(error_ string) *ErrorExt {
	this := ErrorExt{}
	this.Error = error_
	return &this
}

// NewErrorExtWithDefaults instantiates a new ErrorExt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorExtWithDefaults() *ErrorExt {
	this := ErrorExt{}
	return &this
}

// GetError returns the Error field value
func (o *ErrorExt) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ErrorExt) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *ErrorExt) SetError(v string) {
	o.Error = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *ErrorExt) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorExt) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *ErrorExt) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *ErrorExt) SetRequestId(v string) {
	o.RequestId = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ErrorExt) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorExt) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ErrorExt) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *ErrorExt) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o ErrorExt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorExt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	if !IsNil(o.RequestId) {
		toSerialize["request_id"] = o.RequestId
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *ErrorExt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varErrorExt := _ErrorExt{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varErrorExt)

	if err != nil {
		return err
	}

	*o = ErrorExt(varErrorExt)

	return err
}

type NullableErrorExt struct {
	value *ErrorExt
	isSet bool
}

func (v NullableErrorExt) Get() *ErrorExt {
	return v.value
}

func (v *NullableErrorExt) Set(val *ErrorExt) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorExt) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorExt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorExt(val *ErrorExt) *NullableErrorExt {
	return &NullableErrorExt{value: val, isSet: true}
}

func (v NullableErrorExt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorExt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


