/*
Mender API

Combined API specification for the features of the different Mender backend services, suitable for code generation applications

API version: 1
Contact: support@mender.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AzureSharedAccessSecret type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AzureSharedAccessSecret{}

// AzureSharedAccessSecret Shared Access Secret is an authentication mechanism in the form of a connection string for Azure IoT Hub.
type AzureSharedAccessSecret struct {
	// The credential type
	Type             string `json:"type"`
	ConnectionString string `json:"connection_string"`
}

type _AzureSharedAccessSecret AzureSharedAccessSecret

// NewAzureSharedAccessSecret instantiates a new AzureSharedAccessSecret object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureSharedAccessSecret(type_ string, connectionString string) *AzureSharedAccessSecret {
	this := AzureSharedAccessSecret{}
	this.Type = type_
	this.ConnectionString = connectionString
	return &this
}

// NewAzureSharedAccessSecretWithDefaults instantiates a new AzureSharedAccessSecret object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureSharedAccessSecretWithDefaults() *AzureSharedAccessSecret {
	this := AzureSharedAccessSecret{}
	return &this
}

// GetType returns the Type field value
func (o *AzureSharedAccessSecret) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AzureSharedAccessSecret) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AzureSharedAccessSecret) SetType(v string) {
	o.Type = v
}

// GetConnectionString returns the ConnectionString field value
func (o *AzureSharedAccessSecret) GetConnectionString() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionString
}

// GetConnectionStringOk returns a tuple with the ConnectionString field value
// and a boolean to check if the value has been set.
func (o *AzureSharedAccessSecret) GetConnectionStringOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionString, true
}

// SetConnectionString sets field value
func (o *AzureSharedAccessSecret) SetConnectionString(v string) {
	o.ConnectionString = v
}

func (o AzureSharedAccessSecret) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AzureSharedAccessSecret) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["connection_string"] = o.ConnectionString
	return toSerialize, nil
}

func (o *AzureSharedAccessSecret) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"connection_string",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAzureSharedAccessSecret := _AzureSharedAccessSecret{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAzureSharedAccessSecret)

	if err != nil {
		return err
	}

	*o = AzureSharedAccessSecret(varAzureSharedAccessSecret)

	return err
}

type NullableAzureSharedAccessSecret struct {
	value *AzureSharedAccessSecret
	isSet bool
}

func (v NullableAzureSharedAccessSecret) Get() *AzureSharedAccessSecret {
	return v.value
}

func (v *NullableAzureSharedAccessSecret) Set(val *AzureSharedAccessSecret) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureSharedAccessSecret) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureSharedAccessSecret) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureSharedAccessSecret(val *AzureSharedAccessSecret) *NullableAzureSharedAccessSecret {
	return &NullableAzureSharedAccessSecret{value: val, isSet: true}
}

func (v NullableAzureSharedAccessSecret) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureSharedAccessSecret) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
