/*
Mender API

Combined API specification for the features of the different Mender backend services, suitable for code generation applications

API version: 1
Contact: support@mender.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeploymentLog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentLog{}

// DeploymentLog struct for DeploymentLog
type DeploymentLog struct {
	// Array of log entries of a deployment
	Messages []DeploymentLogMessagesInner `json:"messages"`
}

type _DeploymentLog DeploymentLog

// NewDeploymentLog instantiates a new DeploymentLog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentLog(messages []DeploymentLogMessagesInner) *DeploymentLog {
	this := DeploymentLog{}
	this.Messages = messages
	return &this
}

// NewDeploymentLogWithDefaults instantiates a new DeploymentLog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentLogWithDefaults() *DeploymentLog {
	this := DeploymentLog{}
	return &this
}

// GetMessages returns the Messages field value
func (o *DeploymentLog) GetMessages() []DeploymentLogMessagesInner {
	if o == nil {
		var ret []DeploymentLogMessagesInner
		return ret
	}

	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value
// and a boolean to check if the value has been set.
func (o *DeploymentLog) GetMessagesOk() ([]DeploymentLogMessagesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages, true
}

// SetMessages sets field value
func (o *DeploymentLog) SetMessages(v []DeploymentLogMessagesInner) {
	o.Messages = v
}

func (o DeploymentLog) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentLog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["messages"] = o.Messages
	return toSerialize, nil
}

func (o *DeploymentLog) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeploymentLog := _DeploymentLog{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeploymentLog)

	if err != nil {
		return err
	}

	*o = DeploymentLog(varDeploymentLog)

	return err
}

type NullableDeploymentLog struct {
	value *DeploymentLog
	isSet bool
}

func (v NullableDeploymentLog) Get() *DeploymentLog {
	return v.value
}

func (v *NullableDeploymentLog) Set(val *DeploymentLog) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentLog) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentLog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentLog(val *DeploymentLog) *NullableDeploymentLog {
	return &NullableDeploymentLog{value: val, isSet: true}
}

func (v NullableDeploymentLog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentLog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
