#
# .openapi-generator-config.yml
# - https://openapi-generator.tech
#
additionalProperties:
  generateSourceCodeOnly: true
  hideGenerationTimestamp: true
  packageName: "client"
  withGoMod: false

globalProperties:
  apiDocs: false
  apiTests: false
  modelDocs: false
  modelTests: false
