services:
  generate-client:
    volumes:
      - ../../:/backend
    working_dir: /backend/pkg/api
    image: openapitools/openapi-generator-cli:v7.20.0
    command:
      - generate
      - -i=/backend/docs/api/dist/openapi.yaml
      - -o=client
      - -g=go
      - -c=.openapi-generator.yaml
  generate-mocks:
    image: vektra/mockery:v3.7.0
    volumes:
      - ../../:/backend
    working_dir: /backend/pkg/api
