# flake8: noqa

# import apis into api package
from mender_client.api.deployments_device_api_api import DeploymentsDeviceAPIApi
from mender_client.api.deployments_internal_api_internal_api_api import DeploymentsInternalAPIInternalAPIApi
from mender_client.api.deployments_management_api_api import DeploymentsManagementAPIApi
from mender_client.api.deployments_v2_management_api_api import DeploymentsV2ManagementAPIApi
from mender_client.api.device_authentication_device_api_api import DeviceAuthenticationDeviceAPIApi
from mender_client.api.device_authentication_internal_api_api import DeviceAuthenticationInternalAPIApi
from mender_client.api.device_authentication_management_api_api import DeviceAuthenticationManagementAPIApi
from mender_client.api.device_configure_device_api_api import DeviceConfigureDeviceAPIApi
from mender_client.api.device_configure_internal_api_api import DeviceConfigureInternalAPIApi
from mender_client.api.device_configure_management_api_api import DeviceConfigureManagementAPIApi
from mender_client.api.device_connect_device_api_api import DeviceConnectDeviceAPIApi
from mender_client.api.device_connect_internal_api_api import DeviceConnectInternalAPIApi
from mender_client.api.device_connect_management_api_api import DeviceConnectManagementAPIApi
from mender_client.api.device_inventory_device_api_api import DeviceInventoryDeviceAPIApi
from mender_client.api.device_inventory_internal_api_api import DeviceInventoryInternalAPIApi
from mender_client.api.device_inventory_management_api_api import DeviceInventoryManagementAPIApi
from mender_client.api.device_inventory_filters_and_search_internal_api_api import DeviceInventoryFiltersAndSearchInternalAPIApi
from mender_client.api.device_inventory_filters_and_search_management_api_api import DeviceInventoryFiltersAndSearchManagementAPIApi
from mender_client.api.io_t_manager_internal_api_api import IoTManagerInternalAPIApi
from mender_client.api.io_t_manager_management_api_api import IoTManagerManagementAPIApi
from mender_client.api.user_administration_management_api_api import UserAdministrationManagementAPIApi
from mender_client.api.user_administration_and_authentication_internal_api_api import UserAdministrationAndAuthenticationInternalAPIApi
from mender_client.api.workflows_other_api import WorkflowsOtherApi

