FROM python:3.14-trixie
WORKDIR /tests

# Install mender-artifact
RUN \
  apt-get update && \
  apt-get install --assume-yes \
  apt-transport-https \
  ca-certificates \
  gnupg && \
  curl -fsSL https://downloads.mender.io/repos/debian/gpg | tee /etc/apt/trusted.gpg.d/mender.asc | \
  gpg --show-keys --with-fingerprint && \
  sed -i.bak -e "\,https://downloads.mender.io/repos/workstation-tools,d" /etc/apt/sources.list \
  echo "deb [arch=$(dpkg --print-architecture)] https://downloads.mender.io/repos/workstation-tools debian/trixie/stable main" | \
  tee /etc/apt/sources.list.d/mender.list && \
  apt-get update && \
  apt-get install --assume-yes mender-artifact

# Install docker
RUN \
  install -m 0755 -d /etc/apt/keyrings && \
  curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc && \
  chmod a+r /etc/apt/keyrings/docker.asc
RUN . /etc/os-release && \
  cat > /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/debian
Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
Components: stable
Signed-By: /etc/apt/keyrings/docker.asc
EOF

RUN \
  apt-get update -q && \
  apt-get install --assume-yes docker-ce docker-ce-cli containerd.io docker-compose-plugin

# Install python dependencies
COPY requirements-integration.txt .
RUN pip3 install --no-cache-dir -r requirements-integration.txt && \
  apt-get install --assume-yes libzbar0

ENV GO_VERSION=1.25.7

RUN GOARCH=$(dpkg --print-architecture) && \
  curl -L "https://go.dev/dl/go${GO_VERSION}.linux-${GOARCH}.tar.gz" | tar -C /usr/local -xz
ENV PATH="${PATH}:/usr/local/go/bin"
ENV GOPATH=/go
ENV PATH=$PATH:$GOPATH/bin
RUN go version

ENTRYPOINT ["python3", "-m", "pytest"]
