// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mendersoftware/mender-server/pkg/mongo/v2/oid"
	"github.com/mendersoftware/mender-server/services/useradm/jwt"
	"github.com/mendersoftware/mender-server/services/useradm/model"
	mock "github.com/stretchr/testify/mock"
)

// NewDataStore creates a new instance of DataStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &DataStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// DataStore is an autogenerated mock type for the DataStore type
type DataStore struct {
	mock.Mock
}

type DataStore_Expecter struct {
	mock *mock.Mock
}

func (_m *DataStore) EXPECT() *DataStore_Expecter {
	return &DataStore_Expecter{mock: &_m.Mock}
}

// CountPersonalAccessTokens provides a mock function for the type DataStore
func (_mock *DataStore) CountPersonalAccessTokens(ctx context.Context, userID string) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountPersonalAccessTokens")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataStore_CountPersonalAccessTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountPersonalAccessTokens'
type DataStore_CountPersonalAccessTokens_Call struct {
	*mock.Call
}

// CountPersonalAccessTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *DataStore_Expecter) CountPersonalAccessTokens(ctx any, userID any) *DataStore_CountPersonalAccessTokens_Call {
	return &DataStore_CountPersonalAccessTokens_Call{Call: _e.mock.On("CountPersonalAccessTokens", ctx, userID)}
}

func (_c *DataStore_CountPersonalAccessTokens_Call) Run(run func(ctx context.Context, userID string)) *DataStore_CountPersonalAccessTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataStore_CountPersonalAccessTokens_Call) Return(n int64, err error) *DataStore_CountPersonalAccessTokens_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *DataStore_CountPersonalAccessTokens_Call) RunAndReturn(run func(ctx context.Context, userID string) (int64, error)) *DataStore_CountPersonalAccessTokens_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type DataStore
func (_mock *DataStore) CreateUser(ctx context.Context, u *model.User) error {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = returnFunc(ctx, u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataStore_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type DataStore_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - u *model.User
func (_e *DataStore_Expecter) CreateUser(ctx any, u any) *DataStore_CreateUser_Call {
	return &DataStore_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, u)}
}

func (_c *DataStore_CreateUser_Call) Run(run func(ctx context.Context, u *model.User)) *DataStore_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.User
		if args[1] != nil {
			arg1 = args[1].(*model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataStore_CreateUser_Call) Return(err error) *DataStore_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataStore_CreateUser_Call) RunAndReturn(run func(ctx context.Context, u *model.User) error) *DataStore_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteToken provides a mock function for the type DataStore
func (_mock *DataStore) DeleteToken(ctx context.Context, userID oid.ObjectID, tokenID oid.ObjectID) error {
	ret := _mock.Called(ctx, userID, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oid.ObjectID, oid.ObjectID) error); ok {
		r0 = returnFunc(ctx, userID, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataStore_DeleteToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteToken'
type DataStore_DeleteToken_Call struct {
	*mock.Call
}

// DeleteToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID oid.ObjectID
//   - tokenID oid.ObjectID
func (_e *DataStore_Expecter) DeleteToken(ctx any, userID any, tokenID any) *DataStore_DeleteToken_Call {
	return &DataStore_DeleteToken_Call{Call: _e.mock.On("DeleteToken", ctx, userID, tokenID)}
}

func (_c *DataStore_DeleteToken_Call) Run(run func(ctx context.Context, userID oid.ObjectID, tokenID oid.ObjectID)) *DataStore_DeleteToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oid.ObjectID
		if args[1] != nil {
			arg1 = args[1].(oid.ObjectID)
		}
		var arg2 oid.ObjectID
		if args[2] != nil {
			arg2 = args[2].(oid.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DataStore_DeleteToken_Call) Return(err error) *DataStore_DeleteToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataStore_DeleteToken_Call) RunAndReturn(run func(ctx context.Context, userID oid.ObjectID, tokenID oid.ObjectID) error) *DataStore_DeleteToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTokens provides a mock function for the type DataStore
func (_mock *DataStore) DeleteTokens(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTokens")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataStore_DeleteTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTokens'
type DataStore_DeleteTokens_Call struct {
	*mock.Call
}

// DeleteTokens is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DataStore_Expecter) DeleteTokens(ctx any) *DataStore_DeleteTokens_Call {
	return &DataStore_DeleteTokens_Call{Call: _e.mock.On("DeleteTokens", ctx)}
}

func (_c *DataStore_DeleteTokens_Call) Run(run func(ctx context.Context)) *DataStore_DeleteTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DataStore_DeleteTokens_Call) Return(err error) *DataStore_DeleteTokens_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataStore_DeleteTokens_Call) RunAndReturn(run func(ctx context.Context) error) *DataStore_DeleteTokens_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTokensByUserId provides a mock function for the type DataStore
func (_mock *DataStore) DeleteTokensByUserId(ctx context.Context, userId string) error {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTokensByUserId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataStore_DeleteTokensByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTokensByUserId'
type DataStore_DeleteTokensByUserId_Call struct {
	*mock.Call
}

// DeleteTokensByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *DataStore_Expecter) DeleteTokensByUserId(ctx any, userId any) *DataStore_DeleteTokensByUserId_Call {
	return &DataStore_DeleteTokensByUserId_Call{Call: _e.mock.On("DeleteTokensByUserId", ctx, userId)}
}

func (_c *DataStore_DeleteTokensByUserId_Call) Run(run func(ctx context.Context, userId string)) *DataStore_DeleteTokensByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataStore_DeleteTokensByUserId_Call) Return(err error) *DataStore_DeleteTokensByUserId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataStore_DeleteTokensByUserId_Call) RunAndReturn(run func(ctx context.Context, userId string) error) *DataStore_DeleteTokensByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTokensByUserIdExceptCurrentOne provides a mock function for the type DataStore
func (_mock *DataStore) DeleteTokensByUserIdExceptCurrentOne(ctx context.Context, userId string, tokenID oid.ObjectID) error {
	ret := _mock.Called(ctx, userId, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTokensByUserIdExceptCurrentOne")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, oid.ObjectID) error); ok {
		r0 = returnFunc(ctx, userId, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataStore_DeleteTokensByUserIdExceptCurrentOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTokensByUserIdExceptCurrentOne'
type DataStore_DeleteTokensByUserIdExceptCurrentOne_Call struct {
	*mock.Call
}

// DeleteTokensByUserIdExceptCurrentOne is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - tokenID oid.ObjectID
func (_e *DataStore_Expecter) DeleteTokensByUserIdExceptCurrentOne(ctx any, userId any, tokenID any) *DataStore_DeleteTokensByUserIdExceptCurrentOne_Call {
	return &DataStore_DeleteTokensByUserIdExceptCurrentOne_Call{Call: _e.mock.On("DeleteTokensByUserIdExceptCurrentOne", ctx, userId, tokenID)}
}

func (_c *DataStore_DeleteTokensByUserIdExceptCurrentOne_Call) Run(run func(ctx context.Context, userId string, tokenID oid.ObjectID)) *DataStore_DeleteTokensByUserIdExceptCurrentOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 oid.ObjectID
		if args[2] != nil {
			arg2 = args[2].(oid.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DataStore_DeleteTokensByUserIdExceptCurrentOne_Call) Return(err error) *DataStore_DeleteTokensByUserIdExceptCurrentOne_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataStore_DeleteTokensByUserIdExceptCurrentOne_Call) RunAndReturn(run func(ctx context.Context, userId string, tokenID oid.ObjectID) error) *DataStore_DeleteTokensByUserIdExceptCurrentOne_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type DataStore
func (_mock *DataStore) DeleteUser(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataStore_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type DataStore_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *DataStore_Expecter) DeleteUser(ctx any, id any) *DataStore_DeleteUser_Call {
	return &DataStore_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *DataStore_DeleteUser_Call) Run(run func(ctx context.Context, id string)) *DataStore_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataStore_DeleteUser_Call) Return(err error) *DataStore_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataStore_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id string) error) *DataStore_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureSessionTokensLimit provides a mock function for the type DataStore
func (_mock *DataStore) EnsureSessionTokensLimit(ctx context.Context, userID oid.ObjectID, sessionsLimit int) error {
	ret := _mock.Called(ctx, userID, sessionsLimit)

	if len(ret) == 0 {
		panic("no return value specified for EnsureSessionTokensLimit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oid.ObjectID, int) error); ok {
		r0 = returnFunc(ctx, userID, sessionsLimit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataStore_EnsureSessionTokensLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureSessionTokensLimit'
type DataStore_EnsureSessionTokensLimit_Call struct {
	*mock.Call
}

// EnsureSessionTokensLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID oid.ObjectID
//   - sessionsLimit int
func (_e *DataStore_Expecter) EnsureSessionTokensLimit(ctx any, userID any, sessionsLimit any) *DataStore_EnsureSessionTokensLimit_Call {
	return &DataStore_EnsureSessionTokensLimit_Call{Call: _e.mock.On("EnsureSessionTokensLimit", ctx, userID, sessionsLimit)}
}

func (_c *DataStore_EnsureSessionTokensLimit_Call) Run(run func(ctx context.Context, userID oid.ObjectID, sessionsLimit int)) *DataStore_EnsureSessionTokensLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oid.ObjectID
		if args[1] != nil {
			arg1 = args[1].(oid.ObjectID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DataStore_EnsureSessionTokensLimit_Call) Return(err error) *DataStore_EnsureSessionTokensLimit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataStore_EnsureSessionTokensLimit_Call) RunAndReturn(run func(ctx context.Context, userID oid.ObjectID, sessionsLimit int) error) *DataStore_EnsureSessionTokensLimit_Call {
	_c.Call.Return(run)
	return _c
}

// GetPersonalAccessTokens provides a mock function for the type DataStore
func (_mock *DataStore) GetPersonalAccessTokens(ctx context.Context, userID string) ([]model.PersonalAccessToken, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPersonalAccessTokens")
	}

	var r0 []model.PersonalAccessToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.PersonalAccessToken, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.PersonalAccessToken); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PersonalAccessToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataStore_GetPersonalAccessTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPersonalAccessTokens'
type DataStore_GetPersonalAccessTokens_Call struct {
	*mock.Call
}

// GetPersonalAccessTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *DataStore_Expecter) GetPersonalAccessTokens(ctx any, userID any) *DataStore_GetPersonalAccessTokens_Call {
	return &DataStore_GetPersonalAccessTokens_Call{Call: _e.mock.On("GetPersonalAccessTokens", ctx, userID)}
}

func (_c *DataStore_GetPersonalAccessTokens_Call) Run(run func(ctx context.Context, userID string)) *DataStore_GetPersonalAccessTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataStore_GetPersonalAccessTokens_Call) Return(personalAccessTokens []model.PersonalAccessToken, err error) *DataStore_GetPersonalAccessTokens_Call {
	_c.Call.Return(personalAccessTokens, err)
	return _c
}

func (_c *DataStore_GetPersonalAccessTokens_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]model.PersonalAccessToken, error)) *DataStore_GetPersonalAccessTokens_Call {
	_c.Call.Return(run)
	return _c
}

// GetSettings provides a mock function for the type DataStore
func (_mock *DataStore) GetSettings(ctx context.Context) (*model.Settings, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSettings")
	}

	var r0 *model.Settings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*model.Settings, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *model.Settings); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Settings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataStore_GetSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSettings'
type DataStore_GetSettings_Call struct {
	*mock.Call
}

// GetSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DataStore_Expecter) GetSettings(ctx any) *DataStore_GetSettings_Call {
	return &DataStore_GetSettings_Call{Call: _e.mock.On("GetSettings", ctx)}
}

func (_c *DataStore_GetSettings_Call) Run(run func(ctx context.Context)) *DataStore_GetSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DataStore_GetSettings_Call) Return(settings *model.Settings, err error) *DataStore_GetSettings_Call {
	_c.Call.Return(settings, err)
	return _c
}

func (_c *DataStore_GetSettings_Call) RunAndReturn(run func(ctx context.Context) (*model.Settings, error)) *DataStore_GetSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenById provides a mock function for the type DataStore
func (_mock *DataStore) GetTokenById(ctx context.Context, id oid.ObjectID) (*jwt.Token, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenById")
	}

	var r0 *jwt.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oid.ObjectID) (*jwt.Token, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oid.ObjectID) *jwt.Token); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oid.ObjectID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataStore_GetTokenById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenById'
type DataStore_GetTokenById_Call struct {
	*mock.Call
}

// GetTokenById is a helper method to define mock.On call
//   - ctx context.Context
//   - id oid.ObjectID
func (_e *DataStore_Expecter) GetTokenById(ctx any, id any) *DataStore_GetTokenById_Call {
	return &DataStore_GetTokenById_Call{Call: _e.mock.On("GetTokenById", ctx, id)}
}

func (_c *DataStore_GetTokenById_Call) Run(run func(ctx context.Context, id oid.ObjectID)) *DataStore_GetTokenById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oid.ObjectID
		if args[1] != nil {
			arg1 = args[1].(oid.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataStore_GetTokenById_Call) Return(token *jwt.Token, err error) *DataStore_GetTokenById_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *DataStore_GetTokenById_Call) RunAndReturn(run func(ctx context.Context, id oid.ObjectID) (*jwt.Token, error)) *DataStore_GetTokenById_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAndPasswordById provides a mock function for the type DataStore
func (_mock *DataStore) GetUserAndPasswordById(ctx context.Context, id string) (*model.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAndPasswordById")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataStore_GetUserAndPasswordById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAndPasswordById'
type DataStore_GetUserAndPasswordById_Call struct {
	*mock.Call
}

// GetUserAndPasswordById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *DataStore_Expecter) GetUserAndPasswordById(ctx any, id any) *DataStore_GetUserAndPasswordById_Call {
	return &DataStore_GetUserAndPasswordById_Call{Call: _e.mock.On("GetUserAndPasswordById", ctx, id)}
}

func (_c *DataStore_GetUserAndPasswordById_Call) Run(run func(ctx context.Context, id string)) *DataStore_GetUserAndPasswordById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataStore_GetUserAndPasswordById_Call) Return(user *model.User, err error) *DataStore_GetUserAndPasswordById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *DataStore_GetUserAndPasswordById_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.User, error)) *DataStore_GetUserAndPasswordById_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type DataStore
func (_mock *DataStore) GetUserByEmail(ctx context.Context, email model.Email) (*model.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Email) (*model.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Email) *model.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Email) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataStore_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type DataStore_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email model.Email
func (_e *DataStore_Expecter) GetUserByEmail(ctx any, email any) *DataStore_GetUserByEmail_Call {
	return &DataStore_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *DataStore_GetUserByEmail_Call) Run(run func(ctx context.Context, email model.Email)) *DataStore_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Email
		if args[1] != nil {
			arg1 = args[1].(model.Email)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataStore_GetUserByEmail_Call) Return(user *model.User, err error) *DataStore_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *DataStore_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email model.Email) (*model.User, error)) *DataStore_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function for the type DataStore
func (_mock *DataStore) GetUserById(ctx context.Context, id string) (*model.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataStore_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type DataStore_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *DataStore_Expecter) GetUserById(ctx any, id any) *DataStore_GetUserById_Call {
	return &DataStore_GetUserById_Call{Call: _e.mock.On("GetUserById", ctx, id)}
}

func (_c *DataStore_GetUserById_Call) Run(run func(ctx context.Context, id string)) *DataStore_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataStore_GetUserById_Call) Return(user *model.User, err error) *DataStore_GetUserById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *DataStore_GetUserById_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.User, error)) *DataStore_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSettings provides a mock function for the type DataStore
func (_mock *DataStore) GetUserSettings(ctx context.Context, userID string) (*model.Settings, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSettings")
	}

	var r0 *model.Settings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Settings, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Settings); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Settings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataStore_GetUserSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSettings'
type DataStore_GetUserSettings_Call struct {
	*mock.Call
}

// GetUserSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *DataStore_Expecter) GetUserSettings(ctx any, userID any) *DataStore_GetUserSettings_Call {
	return &DataStore_GetUserSettings_Call{Call: _e.mock.On("GetUserSettings", ctx, userID)}
}

func (_c *DataStore_GetUserSettings_Call) Run(run func(ctx context.Context, userID string)) *DataStore_GetUserSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataStore_GetUserSettings_Call) Return(settings *model.Settings, err error) *DataStore_GetUserSettings_Call {
	_c.Call.Return(settings, err)
	return _c
}

func (_c *DataStore_GetUserSettings_Call) RunAndReturn(run func(ctx context.Context, userID string) (*model.Settings, error)) *DataStore_GetUserSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type DataStore
func (_mock *DataStore) GetUsers(ctx context.Context, fltr model.UserFilter) ([]model.User, error) {
	ret := _mock.Called(ctx, fltr)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserFilter) ([]model.User, error)); ok {
		return returnFunc(ctx, fltr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserFilter) []model.User); ok {
		r0 = returnFunc(ctx, fltr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.UserFilter) error); ok {
		r1 = returnFunc(ctx, fltr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataStore_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type DataStore_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - fltr model.UserFilter
func (_e *DataStore_Expecter) GetUsers(ctx any, fltr any) *DataStore_GetUsers_Call {
	return &DataStore_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, fltr)}
}

func (_c *DataStore_GetUsers_Call) Run(run func(ctx context.Context, fltr model.UserFilter)) *DataStore_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserFilter
		if args[1] != nil {
			arg1 = args[1].(model.UserFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataStore_GetUsers_Call) Return(users []model.User, err error) *DataStore_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *DataStore_GetUsers_Call) RunAndReturn(run func(ctx context.Context, fltr model.UserFilter) ([]model.User, error)) *DataStore_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type DataStore
func (_mock *DataStore) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataStore_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type DataStore_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DataStore_Expecter) Ping(ctx any) *DataStore_Ping_Call {
	return &DataStore_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *DataStore_Ping_Call) Run(run func(ctx context.Context)) *DataStore_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DataStore_Ping_Call) Return(err error) *DataStore_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataStore_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *DataStore_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSettings provides a mock function for the type DataStore
func (_mock *DataStore) SaveSettings(ctx context.Context, s *model.Settings, etag string) error {
	ret := _mock.Called(ctx, s, etag)

	if len(ret) == 0 {
		panic("no return value specified for SaveSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Settings, string) error); ok {
		r0 = returnFunc(ctx, s, etag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataStore_SaveSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSettings'
type DataStore_SaveSettings_Call struct {
	*mock.Call
}

// SaveSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - s *model.Settings
//   - etag string
func (_e *DataStore_Expecter) SaveSettings(ctx any, s any, etag any) *DataStore_SaveSettings_Call {
	return &DataStore_SaveSettings_Call{Call: _e.mock.On("SaveSettings", ctx, s, etag)}
}

func (_c *DataStore_SaveSettings_Call) Run(run func(ctx context.Context, s *model.Settings, etag string)) *DataStore_SaveSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Settings
		if args[1] != nil {
			arg1 = args[1].(*model.Settings)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DataStore_SaveSettings_Call) Return(err error) *DataStore_SaveSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataStore_SaveSettings_Call) RunAndReturn(run func(ctx context.Context, s *model.Settings, etag string) error) *DataStore_SaveSettings_Call {
	_c.Call.Return(run)
	return _c
}

// SaveToken provides a mock function for the type DataStore
func (_mock *DataStore) SaveToken(ctx context.Context, token *jwt.Token) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for SaveToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *jwt.Token) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataStore_SaveToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveToken'
type DataStore_SaveToken_Call struct {
	*mock.Call
}

// SaveToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *jwt.Token
func (_e *DataStore_Expecter) SaveToken(ctx any, token any) *DataStore_SaveToken_Call {
	return &DataStore_SaveToken_Call{Call: _e.mock.On("SaveToken", ctx, token)}
}

func (_c *DataStore_SaveToken_Call) Run(run func(ctx context.Context, token *jwt.Token)) *DataStore_SaveToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *jwt.Token
		if args[1] != nil {
			arg1 = args[1].(*jwt.Token)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataStore_SaveToken_Call) Return(err error) *DataStore_SaveToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataStore_SaveToken_Call) RunAndReturn(run func(ctx context.Context, token *jwt.Token) error) *DataStore_SaveToken_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUserSettings provides a mock function for the type DataStore
func (_mock *DataStore) SaveUserSettings(ctx context.Context, userID string, s *model.Settings, etag string) error {
	ret := _mock.Called(ctx, userID, s, etag)

	if len(ret) == 0 {
		panic("no return value specified for SaveUserSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.Settings, string) error); ok {
		r0 = returnFunc(ctx, userID, s, etag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataStore_SaveUserSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUserSettings'
type DataStore_SaveUserSettings_Call struct {
	*mock.Call
}

// SaveUserSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - s *model.Settings
//   - etag string
func (_e *DataStore_Expecter) SaveUserSettings(ctx any, userID any, s any, etag any) *DataStore_SaveUserSettings_Call {
	return &DataStore_SaveUserSettings_Call{Call: _e.mock.On("SaveUserSettings", ctx, userID, s, etag)}
}

func (_c *DataStore_SaveUserSettings_Call) Run(run func(ctx context.Context, userID string, s *model.Settings, etag string)) *DataStore_SaveUserSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.Settings
		if args[2] != nil {
			arg2 = args[2].(*model.Settings)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *DataStore_SaveUserSettings_Call) Return(err error) *DataStore_SaveUserSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataStore_SaveUserSettings_Call) RunAndReturn(run func(ctx context.Context, userID string, s *model.Settings, etag string) error) *DataStore_SaveUserSettings_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLoginTs provides a mock function for the type DataStore
func (_mock *DataStore) UpdateLoginTs(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLoginTs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataStore_UpdateLoginTs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLoginTs'
type DataStore_UpdateLoginTs_Call struct {
	*mock.Call
}

// UpdateLoginTs is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *DataStore_Expecter) UpdateLoginTs(ctx any, id any) *DataStore_UpdateLoginTs_Call {
	return &DataStore_UpdateLoginTs_Call{Call: _e.mock.On("UpdateLoginTs", ctx, id)}
}

func (_c *DataStore_UpdateLoginTs_Call) Run(run func(ctx context.Context, id string)) *DataStore_UpdateLoginTs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataStore_UpdateLoginTs_Call) Return(err error) *DataStore_UpdateLoginTs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataStore_UpdateLoginTs_Call) RunAndReturn(run func(ctx context.Context, id string) error) *DataStore_UpdateLoginTs_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTokenLastUsed provides a mock function for the type DataStore
func (_mock *DataStore) UpdateTokenLastUsed(ctx context.Context, id oid.ObjectID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTokenLastUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oid.ObjectID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataStore_UpdateTokenLastUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTokenLastUsed'
type DataStore_UpdateTokenLastUsed_Call struct {
	*mock.Call
}

// UpdateTokenLastUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id oid.ObjectID
func (_e *DataStore_Expecter) UpdateTokenLastUsed(ctx any, id any) *DataStore_UpdateTokenLastUsed_Call {
	return &DataStore_UpdateTokenLastUsed_Call{Call: _e.mock.On("UpdateTokenLastUsed", ctx, id)}
}

func (_c *DataStore_UpdateTokenLastUsed_Call) Run(run func(ctx context.Context, id oid.ObjectID)) *DataStore_UpdateTokenLastUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oid.ObjectID
		if args[1] != nil {
			arg1 = args[1].(oid.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataStore_UpdateTokenLastUsed_Call) Return(err error) *DataStore_UpdateTokenLastUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataStore_UpdateTokenLastUsed_Call) RunAndReturn(run func(ctx context.Context, id oid.ObjectID) error) *DataStore_UpdateTokenLastUsed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type DataStore
func (_mock *DataStore) UpdateUser(ctx context.Context, id string, u *model.UserUpdate) (*model.User, error) {
	ret := _mock.Called(ctx, id, u)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.UserUpdate) (*model.User, error)); ok {
		return returnFunc(ctx, id, u)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.UserUpdate) *model.User); ok {
		r0 = returnFunc(ctx, id, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *model.UserUpdate) error); ok {
		r1 = returnFunc(ctx, id, u)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataStore_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type DataStore_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - u *model.UserUpdate
func (_e *DataStore_Expecter) UpdateUser(ctx any, id any, u any) *DataStore_UpdateUser_Call {
	return &DataStore_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, id, u)}
}

func (_c *DataStore_UpdateUser_Call) Run(run func(ctx context.Context, id string, u *model.UserUpdate)) *DataStore_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.UserUpdate
		if args[2] != nil {
			arg2 = args[2].(*model.UserUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DataStore_UpdateUser_Call) Return(user *model.User, err error) *DataStore_UpdateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *DataStore_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, id string, u *model.UserUpdate) (*model.User, error)) *DataStore_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
