services:
  s3:
    image: "${MIRROR_REGISTRY:-docker.io}/rustfs/rustfs:1.0.1"
    environment:
      RUSTFS_ACCESS_KEY: "${MENDER_ACCESS_KEY_ID:-mender}"
      RUSTFS_SECRET_KEY: "${MENDER_SECRET_ACCESS_KEY:-thisisnotsecure}"
      RUSTFS_ADDRESS: ":8080"
      RUSTFS_CONSOLE_ADDRESS: ":8081"
      RUSTFS_CONSOLE_ENABLE: "true"
    labels:
      traefik.enable: "true"
      traefik.http.routers.s3.priority: "99999"
      traefik.http.routers.s3.rule:
        (Host(`s3.${MENDER_HOSTNAME:-docker.mender.io}`) ||
        Host(`${MENDER_HOSTNAME:-docker.mender.io}`) ||
        Host(`localhost`)) &&
        PathPrefix(`/mender`)
      traefik.http.services.s3.loadBalancer.server.port: "8080"
    healthcheck:
      test:
        - CMD
        - /usr/bin/nc
        - -z
        - 127.0.0.1
        - "8080"
      interval: 5s
      retries: 10
    volumes:
      - rustfs:/data
volumes:
  rustfs: {}
