openapi: 3.0.1
info:
  title: Device inventory
  description: |
    An API for device attribute management and device grouping.
    Not exposed via the API Gateway - intended for internal use only.
  version: "1"
servers:
- url: http://mender-inventory:8080/api/internal/v1/inventory
paths:
  /health:
    get:
      tags:
      - Internal API
      summary: Check the health of the service
      operationId: Check Health
      responses:
        "204":
          description: |
            Service is healthy and all dependencies are up and running.
          content: {}
        "500":
          description: |
            Unexpected internal error
          content:
            '*/*':
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
            application/json:
              example:
                error: internal error
                request_id: ffd712be-d697-4cb7-814b-88ff1e2eb5f6
        "503":
          description: |
            Service unhealthy / not ready to accept traffic. At least one dependency is not running.
          content:
            '*/*':
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
            application/json:
              example:
                error: "error reaching MongoDB: context deadline exceeded"
                request_id: ffd712be-d697-4cb7-814b-88ff1e2eb5f6
  /alive:
    get:
      tags:
      - Internal API
      summary: |
        Trivial endpoint that unconditionally returns an empty 200 response whenever the API handler is running correctly.
      operationId: Check Liveliness
      responses:
        "204":
          description: Service is up and running.
          content: {}
        "500":
          description: |
            Internal API error
          content:
            '*/*':
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
  /tenants:
    post:
      tags:
      - Internal API
      summary: Create tenant
      description: |
        Create a tenant with provided configuration.
      operationId: Create Tenant
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/TenantNew'
        required: true
      responses:
        "201":
          description: The tenant was created successfully.
          content: {}
        "400":
          description: Missing or malformed request parameters.
          content: {}
        "500":
          description: Unexpected error.
          content:
            '*/*':
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
  /tenants/{tenant_id}/devices:
    post:
      tags:
      - Internal API
      summary: Create a device resource with the supplied set of attributes
      operationId: Initialize Device
      parameters:
      - name: tenant_id
        in: path
        description: ID of given tenant.
        required: true
        schema:
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/DeviceNew'
        required: true
      responses:
        "201":
          description: The device was successfully created.
          headers:
            Location:
              description: URI for the newly created 'Device' resource.
              schema:
                type: string
          content: {}
        "400":
          description: Malformed request body. See error for details.
          content:
            '*/*':
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
        "500":
          description: Internal server error.
          content:
            '*/*':
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
  /tenants/{tenant_id}/devices/{device_id}:
    delete:
      tags:
      - Internal API
      summary: Remove a device from the inventory service
      operationId: Delete Device
      parameters:
      - name: tenant_id
        in: path
        description: ID of given tenant.
        required: true
        schema:
          type: string
      - name: device_id
        in: path
        description: ID of given device.
        required: true
        schema:
          type: string
      responses:
        "204":
          description: Device removed
          content: {}
        "404":
          description: The device was not found.
          content:
            '*/*':
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
        "500":
          description: Internal server error.
          content:
            '*/*':
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
  /tenants/{tenant_id}/devices/status/{status}:
    post:
      tags:
      - Internal API
      summary: Update the status of a list of devices
      description: |
        An API end-point that allows to bulk update the status of a list
        of devices.
      operationId: Update Status of Devices
      parameters:
      - name: tenant_id
        in: path
        description: ID of given tenant.
        required: true
        schema:
          type: string
      - name: status
        in: path
        description: New status to set for the specified devices.
        required: true
        schema:
          type: string
      requestBody:
        description: List of devices.
        content:
          '*/*':
            schema:
              type: array
              description: A list of devices to update.
              example:
              - id: ff8f7099-d842-42f2-9d5b-46a9ad13f90a
                revision: 3
              - id: 80f3ad8f-40f2-429a-8931-b47cebbbe9b3
                revision: 5
              items:
                $ref: '#/components/schemas/DeviceUpdate'
        required: true
      responses:
        "200":
          description: The operation completed successfully.
          content: {}
        "400":
          description: Malformed request body. See error for details.
          content:
            application/json:
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
        "409":
          description: "Write conflict, the request needs to be retried."
          content:
            application/json:
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
        "500":
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
  /tenants/{tenant_id}/device/{device_id}/attribute/scope/{scope}:
    patch:
      tags:
      - Internal API
      summary: Update multiple inventory attributes in a single scope for a device
      description: |
        An API end-point that allows to  update the inventory attributes in
        a single scope for a device.
      operationId: Update Inventory for a Device
      parameters:
      - name: If-Unmodified-Since
        in: header
        description: Skips updating the device if modified after the given RFC1123 timestamp.
        required: false
        schema:
          type: string
      - name: tenant_id
        in: path
        description: ID of given tenant.
        required: true
        schema:
          type: string
      - name: device_id
        in: path
        description: ID of given device.
        required: true
        schema:
          type: string
      - name: scope
        in: path
        description: Scope of the inventory attributes.
        required: true
        schema:
          type: string
      requestBody:
        description: List of inventory attributes to set.
        content:
          '*/*':
            schema:
              type: array
              description: A list of attribute descriptors.
              items:
                $ref: '#/components/schemas/Attribute'
        required: true
      responses:
        "200":
          description: Device inventory successfully updated.
          content: {}
        "400":
          $ref: './common/schemas.yaml#/components/schemas/Error'
        412:
          description: "Precondition failed: If-Unmodified-Since condition not met"
          content:
            application/json:
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
        "500":
          $ref: './common/schemas.yaml#/components/schemas/Error'
  /tenants/{tenant_id}/devices/{device_id}/groups:
    get:
      tags:
      - Internal API
      summary: Get a list of groups the device belongs to
      operationId: Get Device Groups
      parameters:
      - name: tenant_id
        in: path
        description: ID of given tenant.
        required: true
        schema:
          type: string
      - name: device_id
        in: path
        description: Device identifier.
        required: true
        schema:
          type: string
      responses:
        "200":
          description: |
            Successful response.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Groups'
        "400":
          description: Missing or malformed request params or body. See the error
            message for details.
          content: {}
        "404":
          description: The device was not found.
          content:
            '*/*':
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
        "500":
          description: Internal server error.
          content:
            '*/*':
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
  /tenants/{tenant_id}/devices/{device_id}/reindex:
    post:
      tags:
      - Internal API
      summary: Start reindexing device attributes.
      operationId: Start Re-indexing
      parameters:
      - name: service
        in: query
        description: The name of the calling service.
        schema:
          type: string
      - name: device_id
        in: path
        description: ID of the device that needs reindexing.
        required: true
        schema:
          type: string
      - name: tenant_id
        in: path
        description: ID of tenant owning the device.
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Attributes have been re-indexed.
          content: {}
        "400":
          description: Invalid Request.
          content:
            '*/*':
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
        "500":
          description: Internal server error.
          content:
            '*/*':
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
components:
  schemas:
    TenantNew:
      type: object
      properties:
        tenant_id:
          type: string
          description: ID of given tenant.
      description: Tenant configuration.
      example:
        tenant_id: "1234"
    DeviceNew:
      required:
      - id
      type: object
      properties:
        id:
          type: string
          description: Mender-assigned unique ID.
        updated_ts:
          type: string
          description: Timestamp of the most recent attribute update.
        attributes:
          type: array
          description: A list of attribute descriptors.
          items:
            $ref: '#/components/schemas/Attribute'
      example:
        id: 291ae0e5956c69c2267489213df4459d19ed48a806603def19d417d004a4b67e
        attributes:
        - name: ip_addr
          value: 1.2.3.4
          description: IP address
        - name: mac_addr
          value: 00.01:02:03:04:05
          description: MAC address
    Attribute:
      required:
      - name
      - value
      type: object
      properties:
        name:
          type: string
          description: |
            A human readable, unique attribute ID, e.g. 'device_type', 'ip_addr', 'cpu_load', etc.
        description:
          type: string
          description: Attribute description.
        value:
          type: string
          description: |
            The current value of the attribute.

            Attribute type is implicit, inferred from the JSON type.

            Supported types: number, string, array of numbers, array of strings.
            Mixed type arrays are not allowed.
      description: Attribute descriptor.
      example:
        name: ip_addr_eth
        description: Device IP address on ethernet interface
        value: 127.0.0.1
    DeviceUpdate:
      required:
      - id
      - revision
      type: object
      properties:
        id:
          type: string
          description: Device identifier.
        revision:
          type: number
          description: Device object revision.
          format: integer
      description: Object containing device id and device revision of the device to
        update.
    Groups:
      required:
      - groups
      type: object
      properties:
        groups:
          type: array
          description: List of device's groups.
          items:
            type: string
      example:
        groups:
        - test
        - production
