openapi: 3.0.1
info:
  title: Device inventory
  description: |
    An API for uploading device attributes. Intended for use by devices.

    Devices can upload vendor-specific attributes (software/hardware info, health checks, metrics, etc.) of various data types to the backend.
  version: "1"
servers:
- url: https://hosted.mender.io/api/devices/v1/inventory
paths:
  /device/attributes:
    put:
      tags:
      - Device API
      summary: Replace the set of attributes for a device
      description: |
        Replaces the attribute set for the authenticated device with the provided one.
        The device ID is retrieved from the authorization header.

        This method replaces all the attributes with the new set:

        * attributes not provided in the set are removed from the db

        * the values of existing attributes are overwritten

        * attributes assigned for the first time are automatically created
      operationId: Replace Attributes
      requestBody:
        description: A list of attribute descriptors.
        content:
          application/json:
            schema:
              title: ListOfAttributes
              type: array
              example:
              - name: ip_addr
                value: 1.2.3.4
                description: IP address
              - name: mac_addr
                value: 00.01:02:03:04:05
                description: MAC address
              items:
                $ref: '#/components/schemas/Attribute'
        required: true
      responses:
        "200":
          description: Attributes were uploaded successfully.
          content: {}
        "401":
          description: The device is not authenticated.
          content: {}
        "400":
          description: Missing/malformed request parameters or body.
          content:
            application/json:
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
        "500":
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
      security:
      - DeviceJWT: []
    patch:
      tags:
      - Device API
      summary: Assign a set of attributes for a device
      description: |
        Saves the provided attribute set for the authenticated device.
        The device ID is retrieved from the authorization header.

        This method has upsert semantics:

        * the values of existing attributes are overwritten

        * attributes assigned for the first time are automatically created
      operationId: Assign Attributes
      requestBody:
        description: A list of attribute descriptors.
        content:
          application/json:
            schema:
              title: ListOfAttributes
              type: array
              example:
              - name: ip_addr
                value: 1.2.3.4
                description: IP address
              - name: mac_addr
                value: 00.01:02:03:04:05
                description: MAC address
              items:
                $ref: '#/components/schemas/Attribute'
        required: true
      responses:
        "200":
          description: Attributes were uploaded successfully.
          content: {}
        "401":
          description: The device is not authenticated.
          content: {}
        "400":
          description: Missing/malformed request parameters or body.
          content:
            application/json:
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
        "500":
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: './common/schemas.yaml#/components/schemas/Error'
      security:
      - DeviceJWT: []
components:
  schemas:
    Attribute:
      required:
      - name
      - value
      type: object
      properties:
        name:
          type: string
          description: |
            A human readable, unique attribute ID, e.g. 'device_type', 'ip_addr', 'cpu_load', etc.
        description:
          type: string
          description: Attribute description.
        value:
          type: string
          description: |
            The current value of the attribute.

            Attribute type is implicit, inferred from the JSON type.

            Supported types: number, string, array of numbers, array of strings.
            Mixed type arrays are not allowed.
      description: Attribute descriptor.
      example:
        name: ip_addr_eth
        description: Device IP address on ethernet interface
        value: 127.0.0.1
  securitySchemes:
    DeviceJWT:
      type: apiKey
      description: |
        API token issued by Device Authentication service.
        Format: 'Authorization: Bearer [JWT]'
      name: Authorization
      in: header
