// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"os/exec"

	mock "github.com/stretchr/testify/mock"
)

// NewBinaryExecutor creates a new instance of BinaryExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBinaryExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *BinaryExecutor {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &BinaryExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// BinaryExecutor is an autogenerated mock type for the BinaryExecutor type
type BinaryExecutor struct {
	mock.Mock
}

type BinaryExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *BinaryExecutor) EXPECT() *BinaryExecutor_Expecter {
	return &BinaryExecutor_Expecter{mock: &_m.Mock}
}

// Command provides a mock function for the type BinaryExecutor
func (_mock *BinaryExecutor) Command(ctx context.Context, binary string, arg ...string) (*exec.Cmd, error) {
	var tmpRet mock.Arguments
	if len(arg) > 0 {
		tmpRet = _mock.Called(ctx, binary, arg)
	} else {
		tmpRet = _mock.Called(ctx, binary)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Command")
	}

	var r0 *exec.Cmd
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) (*exec.Cmd, error)); ok {
		return returnFunc(ctx, binary, arg...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) *exec.Cmd); ok {
		r0 = returnFunc(ctx, binary, arg...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exec.Cmd)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = returnFunc(ctx, binary, arg...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BinaryExecutor_Command_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Command'
type BinaryExecutor_Command_Call struct {
	*mock.Call
}

// Command is a helper method to define mock.On call
//   - ctx context.Context
//   - binary string
//   - arg ...string
func (_e *BinaryExecutor_Expecter) Command(ctx any, binary any, arg ...any) *BinaryExecutor_Command_Call {
	return &BinaryExecutor_Command_Call{Call: _e.mock.On("Command",
		append([]any{ctx, binary}, arg...)...)}
}

func (_c *BinaryExecutor_Command_Call) Run(run func(ctx context.Context, binary string, arg ...string)) *BinaryExecutor_Command_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BinaryExecutor_Command_Call) Return(cmd *exec.Cmd, err error) *BinaryExecutor_Command_Call {
	_c.Call.Return(cmd, err)
	return _c
}

func (_c *BinaryExecutor_Command_Call) RunAndReturn(run func(ctx context.Context, binary string, arg ...string) (*exec.Cmd, error)) *BinaryExecutor_Command_Call {
	_c.Call.Return(run)
	return _c
}
